// ====================================================================================
// 1. OBJETO DE TRADUÇÕES (i18n)
// ====================================================================================

const translations = {
    "pageTitleIndex": {
        "pt": "LocalRank IA — Pré-Lançamento",
        "en": "LocalRank AI — Pre-Launch",
        "es": "LocalRank IA — Prelanzamiento"
    },
    "pageTitleForm": {
        "pt": "Pré-Lançamento — LocalRank IA",
        "en": "Pre-Launch — LocalRank AI",
        "es": "Prelanzamiento — LocalRank IA"
    },
    "heroTitle": {
        "pt": "Cansado de ver os seus concorrentes no topo do Google Maps?",
        "en": "Tired of seeing your competitors at the top of Google Maps?",
        "es": "¿Cansado de ver a tus competidores en la cima de Google Maps?"
    },
    "heroSubtitle": {
        "pt": "Chegou o <strong>piloto automático para o seu negócio local</strong>. Otimize o seu Perfil de Empresa no Google, responda clientes e atraia mais visitas… <strong>enquanto dorme.</strong>",
        "en": "The <strong>autopilot for your local business</strong> has arrived. Optimize your Google Business Profile, respond to customers, and attract more visits… <strong>while you sleep.</strong>",
        "es": "Ha llegado el <strong>piloto automático para tu negocio local</strong>. Optimiza tu Perfil de Empresa en Google, responde a clientes y atrae más visitas… <strong>mientras duermes.</strong>"
    },
    "btnMegaDiscount": {
        "pt": "Garantir Mega Desconto",
        "en": "Secure Mega Discount",
        "es": "Asegurar Mega Descuento"
    },
    "sectionTitleProblem": {
        "pt": "O Problema",
        "en": "The Problem",
        "es": "El Problema"
    },
    "cardProblem1Title": {
        "pt": "Avaliações sem resposta?",
        "en": "Unanswered Reviews?",
        "es": "¿Reseñas sin respuesta?"
    },
    "cardProblem1Text": {
        "pt": "Cada review ignorado é um cliente perdido e um sinal negativo para o Google.",
        "en": "Every ignored review is a lost customer and a negative signal for Google.",
        "es": "Cada reseña ignorada es un cliente perdido y una señal negativa para Google."
    },
    "cardProblem2Title": {
        "pt": "Perfil desatualizado?",
        "en": "Outdated Profile?",
        "es": "¿Perfil desactualizado?"
    },
    "cardProblem2Text": {
        "pt": "Um perfil inativo perde relevância e posições no ranking todos os dias.",
        "en": "An inactive profile loses relevance and ranking positions every day.",
        "es": "Un perfil inactivo pierde relevancia y posiciones en el ranking todos los días."
    },
    "cardProblem3Title": {
        "pt": "Sem tempo para marketing?",
        "en": "No Time for Marketing?",
        "es": "¿Sin tiempo para marketing?"
    },
    "cardProblem3Text": {
        "pt": "Você tem um negócio para gerir. Não para decifrar algoritmos.",
        "en": "You have a business to run. Not to decipher algorithms.",
        "es": "Tienes un negocio que gestionar. No para descifrar algoritmos."
    },
    "sectionTitleSolution": {
        "pt": "A Solução",
        "en": "The Solution",
        "es": "La Solución"
    },
    "cardSolution1Title": {
        "pt": "Respostas Inteligentes",
        "en": "Smart Responses",
        "es": "Respuestas Inteligentes"
    },
    "cardSolution1Text": {
        "pt": "A IA analisa o sentimento de cada review e cria respostas profissionais.",
        "en": "AI analyzes the sentiment of each review and creates professional responses.",
        "es": "La IA analiza el sentimiento de cada reseña y crea respuestas profesionales."
    },
    "cardSolution2Title": {
        "pt": "Posts Semanais Automáticos",
        "en": "Automatic Weekly Posts",
        "es": "Publicaciones Semanales Automáticas"
    },
    "cardSolution2Text": {
        "pt": "Perfil sempre ativo com conteúdos relevantes gerados pela IA.",
        "en": "Always active profile with relevant content generated by AI.",
        "es": "Perfil siempre activo con contenido relevante generado por IA."
    },
    "cardSolution3Title": {
        "pt": "Relatórios Claros",
        "en": "Clear Reports",
        "es": "Informes Claros"
    },
    "cardSolution3Text": {
        "pt": "Veja crescimento real: mais chamadas, mais visitas, mais clientes.",
        "en": "See real growth: more calls, more visits, more customers.",
        "es": "Vea crecimiento real: más llamadas, más visitas, más clientes."
    },
    "offerTitle": {
        "pt": "Mega Lançamento",
        "en": "Mega Launch",
        "es": "Mega Lanzamiento"
    },
    "offerSubtitle": {
        "pt": "Seja um dos primeiros. <strong>Garanta um desconto que nunca mais se vai repetir.</strong>",
        "en": "Be one of the first. <strong>Secure a discount that will never be repeated.</strong>",
        "es": "Sé uno de los primeros. <strong>Asegura un descuento que nunca se repetirá.</strong>"
    },
    "offerListItem1": {
        "pt": "📆 Período de <strong>7 dias</strong> de teste grátis",
        "en": "📆 <strong>7-day</strong> free trial period",
        "es": "📆 Período de prueba gratuita de <strong>7 días</strong>"
    },
    "offerListItem2": {
        "pt": "🚀 Mais de <strong>60% de desconto</strong> nos primeiros 3 meses",
        "en": "🚀 Over <strong>60% discount</strong> for the first 3 months",
        "es": "🚀 Más del <strong>60% de descuento</strong> durante los primeros 3 meses"
    },
    "offerListItem3": {
        "pt": "⚡ Acesso prioritário antes de todos",
        "en": "⚡ Priority access before everyone else",
        "es": "⚡ Acceso prioritario antes que nadie"
    },
    "offerListItem4": {
        "pt": "💬 Influência direta nas próximas funcionalidades",
        "en": "💬 Direct influence on upcoming features",
        "es": "💬 Influencia directa en las próximas funcionalidades"
    },
    "offerListItem5": {
        "pt": "🎯 Apenas para os <strong>150 primeiros</strong>",
        "en": "🎯 Only for the <strong>first 150</strong>",
        "es": "🎯 Solo para los <strong>primeros 150</strong>"
    },
    "spotsText": {
        "pt": "Restam aproximadamente <strong>67%</strong> das vagas",
        "en": "Approximately <strong>67%</strong> of spots remain",
        "es": "Queda aproximadamente el <strong>67%</strong> de las plazas"
    },
    "footerText": {
        "pt": "© 2025 LocalRank IA — Todos os direitos reservados",
        "en": "© 2025 LocalRank AI — All rights reserved",
        "es": "© 2025 LocalRank IA — Todos los derechos reservados"
    },
    // FORM.HTML STRINGS
    "formTitle": {
        "pt": "Responda às Questões",
        "en": "Answer the Questions",
        "es": "Responde a las Preguntas"
    },
    "formSubtitle": {
        "pt": "Antes de entrar no grupo de pré-lançamento, responda este formulário rápido. Isso ajuda-nos a adaptar melhor o LocalRank IA às suas necessidades.",
        "en": "Before joining the pre-launch group, please answer this quick form. This helps us better adapt LocalRank AI to your needs.",
        "es": "Antes de unirte al grupo de prelanzamiento, responde este formulario rápido. Esto nos ayuda a adaptar mejor LocalRank IA a tus necesidades."
    },
    "labelCountry": {
        "pt": "País",
        "en": "Country",
        "es": "País"
    },
    "selectPlaceholder": {
        "pt": "Selecione",
        "en": "Select",
        "es": "Selecciona"
    },
    "countryPortugal": {
        "pt": "Portugal",
        "en": "Portugal",
        "es": "Portugal"
    },
    "countryBrazil": {
        "pt": "Brasil",
        "en": "Brazil",
        "es": "Brasil"
    },
    "countrySpain": {
        "pt": "Espanha",
        "en": "Spain",
        "es": "España"
    },
    "countryUSA": {
        "pt": "Estados Unidos",
        "en": "United States",
        "es": "Estados Unidos"
    },
    "countryUK": {
        "pt": "Reino Unido",
        "en": "United Kingdom",
        "es": "Reino Unido"
    },
    "countryAngola": {
        "pt": "Angola",
        "en": "Angola",
        "es": "Angola"
    },
    "countryMozambique": {
        "pt": "Moçambique",
        "en": "Mozambique",
        "es": "Mozambique"
    },
    "countryChile": {
        "pt": "Chile",
        "en": "Chile",
        "es": "Chile"
    },
    "countryMexico": {
        "pt": "México",
        "en": "Mexico",
        "es": "México"
    },
    "countryArgentina": {
        "pt": "Argentina",
        "en": "Argentina",
        "es": "Argentina"
    },
    "labelPreferredLang": {
        "pt": "Idioma preferido",
        "en": "Preferred Language",
        "es": "Idioma preferido"
    },
    "langPT": {
        "pt": "Português",
        "en": "Portuguese",
        "es": "Portugués"
    },
    "langEN": {
        "pt": "Inglês",
        "en": "English",
        "es": "Inglés"
    },
    "langES": {
        "pt": "Espanhol",
        "en": "Spanish",
        "es": "Español"
    },
    "labelBusinessType": {
        "pt": "Tipo de negócio",
        "en": "Business Type",
        "es": "Tipo de negocio"
    },
    "placeholderBusinessType": {
        "pt": "Ex: Restaurante, Clínica, Loja...",
        "en": "Ex: Restaurant, Clinic, Store...",
        "es": "Ej: Restaurante, Clínica, Tienda..."
    },
    "labelBusinessSize": {
        "pt": "Tamanho do negócio",
        "en": "Business Size",
        "es": "Tamaño del negocio"
    },
    "sizeSelfEmployed": {
        "pt": "Autônomo",
        "en": "Self-Employed",
        "es": "Autónomo"
    },
    "sizeSmall": {
        "pt": "Pequeno negócio",
        "en": "Small Business",
        "es": "Pequeño negocio"
    },
    "sizeMedium": {
        "pt": "Médio negócio",
        "en": "Medium Business",
        "es": "Mediano negocio"
    },
    "sizeAgency": {
        "pt": "Agência",
        "en": "Agency",
        "es": "Agencia"
    },
    "labelChallenge": {
        "pt": "Maior desafio no Google / Marketing Local",
        "en": "Biggest Challenge in Google / Local Marketing",
        "es": "Mayor desafío en Google / Marketing Local"
    },
    "placeholderChallenge": {
        "pt": "Descreva em poucas palavras",
        "en": "Describe in a few words",
        "es": "Describe en pocas palabras"
    },
    "labelGMB": {
        "pt": "Já utiliza o Google Meu Negócio?",
        "en": "Do you already use Google My Business?",
        "es": "¿Ya utilizas Google My Business?"
    },
    "gmbYes": {
        "pt": "Sim",
        "en": "Yes",
        "es": "Sí"
    },
    "gmbNo": {
        "pt": "Não",
        "en": "No",
        "es": "No"
    },
    "gmbHeardOf": {
        "pt": "Já ouvi falar",
        "en": "I've heard of it",
        "es": "He oído hablar de ello"
    },
    "labelEmail": {
        "pt": "Email (opcional)",
        "en": "Email (optional)",
        "es": "Email (opcional)"
    },
    "placeholderEmail": {
        "pt": "Para novidades e acesso antecipado",
        "en": "For news and early access",
        "es": "Para novedades y acceso anticipado"
    },
    "btnSubmitForm": {
        "pt": "Entrar no Pré-Lançamento",
        "en": "Join Pre-Launch",
        "es": "Unirse al Prelanzamiento"
    },
    "formSuccess": {
        "pt": "Formulário enviado com sucesso! A redirecionar para o grupo de WhatsApp...",
        "en": "Form submitted successfully! Redirecting to the WhatsApp group...",
        "es": "¡Formulario enviado con éxito! Redirigiendo al grupo de WhatsApp..."
    },
    "formError": {
        "pt": "Erro ao enviar o formulário. Por favor, tente novamente.",
        "en": "Error submitting the form. Please try again.",
        "es": "Error al enviar el formulario. Por favor, inténtalo de nuevo."
    }
};

// ====================================================================================
// 2. LÓGICA DE DETEÇÃO E APLICAÇÃO
// ====================================================================================

const DEFAULT_LANG = 'pt';
const SUPPORTED_LANGS = ['pt', 'en', 'es'];

/**
 * Deteta o idioma preferido do utilizador com base no navegador.
 * @returns {string} O código do idioma ('pt', 'en', ou 'es').
 */
function detectLanguage() {
    const browserLang = navigator.language.toLowerCase().split('-')[0];
    
    // Verifica se o idioma do navegador é suportado
    if (SUPPORTED_LANGS.includes(browserLang)) {
        return browserLang;
    }

    // Verifica por idiomas mais amplos (ex: pt-BR, pt-PT -> pt)
    for (const lang of navigator.languages) {
        const baseLang = lang.toLowerCase().split('-')[0];
        if (SUPPORTED_LANGS.includes(baseLang)) {
            return baseLang;
        }
    }

    // Retorna o idioma padrão se não for detetado nenhum suportado
    return DEFAULT_LANG;
}

/**
 * Aplica as traduções a todos os elementos com o atributo data-i18n.
 * @param {string} lang - O código do idioma a aplicar.
 */
function applyTranslation(lang) {
    // 1. Traduzir o corpo do documento
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[key] && translations[key][lang]) {
            element.innerHTML = translations[key][lang];
        }
    });

    // 2. Traduzir placeholders
    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
        const key = element.getAttribute('data-i18n-placeholder');
        if (translations[key] && translations[key][lang]) {
            element.placeholder = translations[key][lang];
        }
    });

    // 3. Traduzir o título da página
    const titleKey = document.title.includes("Pré-Lançamento") ? "pageTitleForm" : "pageTitleIndex";
    if (translations[titleKey] && translations[titleKey][lang]) {
        document.title = translations[titleKey][lang];
    }

    // 4. Atualizar o botão de idioma
    const langSwitch = document.querySelector('.lang-switch');
    if (langSwitch) {
        langSwitch.textContent = lang.toUpperCase();
    }

    // 5. Guardar o idioma na sessão
    localStorage.setItem('currentLang', lang);
}

/**
 * Alterna para o próximo idioma na lista de suportados.
 */
function toggleLanguage() {
    const currentLang = localStorage.getItem('currentLang') || DEFAULT_LANG;
    const currentIndex = SUPPORTED_LANGS.indexOf(currentLang);
    const nextIndex = (currentIndex + 1) % SUPPORTED_LANGS.length;
    const nextLang = SUPPORTED_LANGS[nextIndex];
    applyTranslation(nextLang);
}

// ====================================================================================
// 3. INICIALIZAÇÃO
// ====================================================================================

document.addEventListener('DOMContentLoaded', () => {
    // 1. Detetar ou carregar o idioma
    let initialLang = localStorage.getItem('currentLang');
    if (!initialLang) {
        initialLang = detectLanguage();
    }

    // 2. Aplicar a tradução inicial
    applyTranslation(initialLang);

    // 3. Ligar o botão de alternância
    const langSwitch = document.querySelector('.lang-switch');
    if (langSwitch) {
        langSwitch.addEventListener('click', toggleLanguage);
    }
});
